### Post user's data
POST http://localhost:7070/index.php HTTP/1.1
Content-Type: multipart/form-data; boundary=WebForm

--WebForm
Content-Disposition: form-data; name="full_name"

Jon Doe
--WebForm
Content-Disposition: form-data; name="email"

john1@example.com
--WebForm
Content-Disposition: form-data; name="phone"

+37061006714
--WebForm
Content-Disposition: form-data; name="loan_amount"

7000
--WebForm
Content-Disposition: form-data; name="file"; filename="passport.jpg"
Content-Type: image/jpeg

< ./assets/passport.jpg
--WebForm--